// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlMTjsCq-nL4xCPjsGkxW0nTrxcIa0GJs',
    appId: '1:498943662506:web:3a190970f1ff85732ff3d3',
    messagingSenderId: '498943662506',
    projectId: 'to-do-app-fb735',
    authDomain: 'to-do-app-fb735.firebaseapp.com',
    storageBucket: 'to-do-app-fb735.appspot.com',
    measurementId: 'G-XVWV27P5XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyRjvrKdbgSNtlu_m17AL8RbxM2A47vkI',
    appId: '1:498943662506:android:49ea8d6ad03d2a542ff3d3',
    messagingSenderId: '498943662506',
    projectId: 'to-do-app-fb735',
    storageBucket: 'to-do-app-fb735.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZHUkwrY1KCB1Tz-y62zIApX_NQCc3XXo',
    appId: '1:498943662506:ios:fa90e94b16e4039d2ff3d3',
    messagingSenderId: '498943662506',
    projectId: 'to-do-app-fb735',
    storageBucket: 'to-do-app-fb735.appspot.com',
    androidClientId: '498943662506-l4rc96f04e1sinilv621prcr2nk6rsgr.apps.googleusercontent.com',
    iosClientId: '498943662506-93rt4c290igklgenaebf1p17sretnfbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.furitHubDashbboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZHUkwrY1KCB1Tz-y62zIApX_NQCc3XXo',
    appId: '1:498943662506:ios:fa90e94b16e4039d2ff3d3',
    messagingSenderId: '498943662506',
    projectId: 'to-do-app-fb735',
    storageBucket: 'to-do-app-fb735.appspot.com',
    androidClientId: '498943662506-l4rc96f04e1sinilv621prcr2nk6rsgr.apps.googleusercontent.com',
    iosClientId: '498943662506-93rt4c290igklgenaebf1p17sretnfbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.furitHubDashbboard',
  );
}
